=== Jan-ShianLiu/oneAPI/compiler/2021.1.1/windows/lib/oclfpga/windows64/messages/messages.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="messages">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="message-list" type="messagelist" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="language" type="xs:string" use="required"/>
      <!-- Language code for the messages - for example EN-US -->
      
    </xs:complexType>
    <xs:unique name="messageIDsuniqueAcrossAllmessages">
      <xs:selector xpath="messages"/>
      <xs:field xpath="@identifier"/>
    </xs:unique>
  </xs:element>

  <xs:simpleType name="messageType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="WARN"/>
      <xs:enumeration value="ERROR"/>
      <xs:enumeration value="INFO"/>
      <xs:enumeration value="TEST"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="messagelist">
    <xs:sequence>
      <xs:element name="message" type="message" maxOccurs="unbounded"/>
    </xs:sequence>
    
    <xs:attribute name="type" type="messageType" use="required"/>
    <!-- Message type should be INFO, WARN, ERROR -->
  </xs:complexType>

  <xs:complexType name="message">
    <xs:all>
      <xs:element name="message-text" type="xs:string"/>
      <!-- Messagetext is parameterizable by elements of type parameter. 
    to use the value of a parameter in the message text use %parametername% 
    and it'll be parsed accordingly -->

      <xs:element name="suggestion" type="xs:string"/>
      <!-- A suggestion of how to fix the error/warning-->

      <xs:element name="parameter-list" type="parameterlist"/>
    </xs:all>
    <xs:attribute name="identifier" type="xs:string" use="required"/>
    <!-- identifier you use when calling the message trigger event. ID type forces them to be unique -->
  </xs:complexType>

  <xs:complexType name="parameter">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="description" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="parameterlist">
    <xs:sequence>
      <xs:element name="parameter" type="parameter" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Jan-ShianLiu/oneAPI/compiler/2021.1.1/windows/lib/oclfpga/windows64/messages/messages.xml
<?xml version="1.0" encoding="utf-8" ?>
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="messages.xsd" language="EN-US">
    <message-list type="ERROR">
        <message identifier="UNABLE_TO_FIND_CONTROL_BLOCK">
            <message-text>Unable to find a valid Control block in the design.</message-text>
            <suggestion>The Control block must be at the top level.</suggestion>
        </message>
        <message identifier="MULTIPLE_CONTROL_BLOCKS">
            <message-text>Multiple Control blocks found in the design.</message-text>
            <suggestion>There should only be one Control block in the design. It must be at the top level.</suggestion>
        </message>
        <message identifier="MULTIPLE_BUS_STIMULUS_BLOCKS">
            <message-text>Multiple Bus Stimulus blocks found in the design.</message-text>
            <suggestion>There should only be one Bus Stimulus block in the design. It must be at the top level.</suggestion>
        </message>
        <message identifier="UNABLE_TO_FIND_SIGNALS_BLOCK">
            <message-text>Unable to find a valid Signals block in the design.</message-text>
            <suggestion>The Signals block must be at the top level.</suggestion>
        </message>
        <message identifier="MULTIPLE_SIGNALS_BLOCKS">
            <message-text>Multiple Signals blocks found in the design.</message-text>
            <suggestion>There should only be one Signals block in the design. It must be at the top level.</suggestion>
        </message>
        <message identifier="ILLEGAL_DEVICE_BLOCK_COMBINATION">
            <message-text>Illegal combination of device blocks found in '%subsystem1%' and '%subsystem2%'.</message-text>
            <suggestion>Only one device block is permitted in each subsystem. Remove the device blocks in the lowest level subsystem.</suggestion>
            <parameter-list>
                <parameter name="subsystem1" description="The first subsystem containing a device block"/>
                <parameter name="subsystem2" description="The second subsystem containing a device block"/>
            </parameter-list>
        </message>
        <message identifier="DEVICE_BLOCK_NOT_IN_SUBSYSTEM">
            <message-text>Found device block at the top level of the model.</message-text>
            <suggestion>Device blocks must be within subsystems. Move this device block out of the top level of the model.</suggestion>
        </message>
        <message identifier="COULD_NOT_CONVERT_STRING_DATA">
            <message-text>Can not convert string data.</message-text>
            <suggestion></suggestion>
        </message>
        <message identifier="COULD_NOT_CONVERT_INTYPE_STRING_DATA">
            <message-text>Cannot convert type's string data on [%path%], input port %port%.</message-text>
            <suggestion></suggestion>
            <parameter-list>
                <parameter name="path" description="Simulink path of block"/>
                <parameter name="port" description="input port index"/>
            </parameter-list>
        </message>
        <message identifier="COULD_NOT_CONVERT_OUTTYPE_STRING_DATA">
            <message-text>Cannot convert type's string data on [%path%], output port %port%.</message-text>
            <suggestion></suggestion>
            <parameter-list>
                <parameter name="path" description="Simulink path of block"/>
                <parameter name="port" description="output port index"/>
            </parameter-list>
        </message>
        <message identifier="RECIPROCAL_BLOCK_NOT_SUPPORTED">
            <message-text>The reciprocal block is no longer supported.</message-text>
            <suggestion></suggestion>
        </message>
        <message identifier="DIVIDE_BLOCK_NOT_SUPPORTED">
            <message-text>The divide block is no longer supported.</message-text>
            <suggestion></suggestion>
        </message>
        <message identifier="HANDLE_FOR_BLOCK_NOT_SCALAR_DOUBLE">
            <message-text>Handle for block '%blockname%' (%blocknumber%) is not a scalar double.</message-text>
            <suggestion></suggestion>
            <parameter-list>
                <parameter name="blockname" description="The name of the block with the invalid handle"/>
                <parameter name="blocknumber" description="The index of the block with the invalid handle"/>
            </parameter-list>
        </message>
        <message identifier="NO_CHANNEL_IN_OR_GP_IN_BLOCKS">
            <message-text>Cannot find any Channel-In or GP-In blocks in the design.</message-text>
            <suggestion>Either add Channel-In or GP-In blocks, or disable the automatic testbench.</suggestion>
        </message>
        <message identifier="NO_CHANNEL_OUT_OR_GP_OUT_BLOCKS">
            <message-text>Cannot find any Channel-Out or GP-Out blocks in the design.</message-text>
            <suggestion>Either add Channel-Out or GP-Out blocks, or disable the automatic testbench.</suggestion>
        </message>
        <message identifier="NO_MATCHING_MEMORY">
            <message-text>The read and write ports given for '%memoryname%' list a memory that is not declared.</message-text>
            <suggestion></suggestion>
            <parameter-list>
               <parameter name="memoryname" description="The simulink path to the memory unit that hasnt been declared"/>
            </parameter-list>
        </message>
        <message identifier="MULTIPLE_MEMORIES_WITH_SAME_ID">
            <message-text>Multiple instances of External Memory block are assigned the same identifier</message-text>
            <suggestion></suggestion>
        </message>
        <message identifier="MULTIPLE_MEMORY_PORTS_WITH_SAME_NAME">
            <message-text>External Memory Read/Write blocks '%block1%' and '%block2%' have the same name '%name%', these blocks should be uniquely named in the design</message-text>
            <suggestion></suggestion>
            <parameter-list>
                <parameter name="name" description="Name of the block"/>
                <parameter name="block1" description="Path of the block"/>
                <parameter name="block2" description="Path of the other block"/>
            </parameter-list>
        </message>
        <message identifier="BLOCK_HAS_NO_LIBRARY_REFERENCE">
            <message-text>Block '%blockname%' has no Library Reference - cannot synthesise it.</message-text>
            <suggestion></suggestion>
            <parameter-list>
                <parameter name="blockname" description="The name of the block with no library reference"/>
            </parameter-list>
        </message>
        <message identifier="UNKNOWN_LOOP_TEST">
            <message-text>[%block%] Unknown loop test: "%testvalue%"</message-text>
            <suggestion></suggestion>
            <parameter-list>
                <parameter name="block" description="path to for-loop block"/>
                <parameter name="testvalue" description="The test that is trying to be carried out"/>
            </parameter-list>
        </message>
        <message identifier="INVALID_NUMBER_OF_FIFO_PARAMETERS">
            <message-text>[%block%] Invalid number of Fifo vector parameters.</message-text>
            <suggestion>Fifo needs 3 or 4 parameters in a vector eg. [32 4 16]</suggestion>
            <parameter-list>
                <parameter name="block" description="path to block"/>
            </parameter-list>
        </message>
        <message identifier="CLOCK_RATE_TOO_HIGH">
            <message-text>Clock rate is too high.</message-text>
            <suggestion></suggestion>
        </message>
        <message identifier="BUS_CLOCK_NOT_SYNCHRONOUS">
            <message-text>The system clock frequency %sysfreq% is not a multiple of the bus clock frequency %busfreq%.</message-text>
            <parameter-list>
                <parameter name="sysfreq" description="The frequency of the system clock."/>
                <parameter name="busfreq" description="The frequency of the bus clock."/>
            </parameter-list>
        </message>
        <message identifier="SYS_CLOCK_NOT_VALID">
            <message-text>The system clock frequency %sysfreq% is not a positive number.</message-text>
            <suggestion>Specify a positive number.</suggestion>
            <parameter-list>
                <parameter name="sysfreq" description="The frequency of the system clock."/>
            </parameter-list>
        </message>
        <message identifier="BUS_CLOCK_NOT_VALID">
            <message-text>The bus clock frequency %busfreq% is not a positive number.</message-text>
            <suggestion>Specify a positive number.</suggestion>
            <parameter-list>
                <parameter name="busfreq" description="The frequency of the bus clock."/>
            </parameter-list>
        </message>
        <message identifier="REAL_IMAG_TO_COMPLEX_UNSUPPORTED_INPUT">
            <message-text>The Real-Imag To Complex block '%blockname%' has unsupported input type.</message-text>
            <suggestion>Use input type 'Real and imag' and create the appropriate constant zero inputs to the block.</suggestion>
            <parameter-list>
                <parameter name="blockname" description="The real-imag to complex block in question."/>
            </parameter-list>
        </message>
        <message identifier="COMPLEX_TO_REAL_IMAG_UNSUPPORTED_INPUT">
            <message-text>The Complex To Real-Imag block '%blockname%' has unsupported input type.</message-text>
            <suggestion>Use input type 'Real and imag' and create the appropriate constant zero inputs to the block.</suggestion>
            <parameter-list>
                <parameter name="blockname" description="The complex to real-imag block in question."/>
            </parameter-list>
        </message>
        <message identifier="SELECTOR_NON_INHERITED_SAMPLE_TIME">
